default:
  desc: 帮助文件
  cmds:
    - task -l

deps:
  desc: 下载依赖包
  dir: src
  cmds:
    - ../scripts/deps.sh

init:
  desc: 安装gopm
    cmds:
      - go get -u github.com/gpmgo/gopm

build:
  desc: 编译应用
  cmds:
    - GOPATH=`pwd` go build cmd/main.go

build_linux:
  desc: 交叉编译成linux应用
  cmds:
    - GOPATH=`pwd` CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build cmd/main.go


docker_build:
  desc: 构建docker镜像
  cmds:
      - task: build_linux
      - docker build -t kchain .
      - docker tag kchain registry.yuanbenlian.com/yuanben/kchain

docker_push:
  desc: docker push
  cmds:
      - docker push registry.yuanbenlian.com/yuanben/kchain

docker_test:
  desc: kchain docker test
  cmds:
    - ls * | grep example_data || mkdir example_data
    - docker run --rm -it -v `pwd`/example_data:/kdata -p 46656:46656 -p 9000:9000 kchain init
    - docker run --rm -it -v `pwd`/example_data:/kdata -p 46656:46656 -p 9000:9000 kchain
    - rm -rf example_data


docker_services_test:
  desc: kchain services docker test
  cmds:
      - docker run --rm -it -v `pwd`/d1:/kdata -p 46656:46656 -p 9000:9000 kchain /app/kchain --home /kdata
